databases:
  # PostgreSQL Database
  - name: fieldelevate-db
    databaseName: fieldelevate
    user: fieldelevate
    plan: free

  # Redis Instance
  - name: fieldelevate-redis
    type: redis
    plan: free

services:
  # Main Application Server (includes frontend)
  - type: web
    name: fieldelevate-main
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fieldelevate-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fieldelevate-redis
          property: connectionString
      - fromGroup: field-elevate-shared
    
  # MCP Hub - The main orchestrator
  - type: web
    name: fieldelevate-mcp-hub
    env: node
    buildCommand: cd mcp-hub && npm install && npm run build
    startCommand: cd mcp-hub && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fieldelevate-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fieldelevate-redis
          property: connectionString
      - key: MCP_HUB_URL
        value: https://fieldelevate-mcp-hub.onrender.com
      - fromGroup: field-elevate-shared
    
  # Data Hub Service
  - type: web
    name: fieldelevate-data-hub
    env: node
    buildCommand: cd data-hub && npm install
    startCommand: cd data-hub && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: fieldelevate-redis
          property: connectionString
      - key: MCP_HUB_URL
        value: https://fieldelevate-mcp-hub.onrender.com
      - fromGroup: field-elevate-shared

  # AI COO Service
  - type: web
    name: fieldelevate-ai-coo
    env: node
    buildCommand: cd ai-coo && npm install && npm run build
    startCommand: cd ai-coo && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: fieldelevate-redis
          property: connectionString
      - key: MCP_HUB_URL
        value: https://fieldelevate-mcp-hub.onrender.com
      - fromGroup: field-elevate-shared
      