#!/bin/bash

echo "🔍 Railway Debug Helper"
echo "====================="
echo ""
echo "Since you can't login to Railway CLI from here, please run these commands on your local machine:"
echo ""
echo "1️⃣ First, login to Railway:"
echo "   railway login"
echo ""
echo "2️⃣ Then run these commands to debug:"
echo ""
echo "📋 Get full deployment logs:"
echo "   railway logs > railway-logs.txt"
echo ""
echo "🏗️ Get build logs:"
echo "   railway logs --build > railway-build-logs.txt"
echo ""
echo "🔧 Check environment variables:"
echo "   railway variables"
echo ""
echo "📊 Check service status:"
echo "   railway status"
echo ""
echo "3️⃣ Or check in Railway Dashboard:"
echo "   - Go to your project"
echo "   - Click on the deployment"
echo "   - Look for the FULL error message (not just 'Node.js v20.19.2')"
echo ""
echo "4️⃣ Common issues to check:"
echo "   ❓ Is DATABASE_URL set correctly?"
echo "   ❓ Is PORT environment variable being overridden?"
echo "   ❓ Are there any missing dependencies?"
echo "   ❓ Is the public/index.html file present?"
echo ""
echo "5️⃣ Quick fix to try:"
echo "   In Railway Dashboard, add this variable:"
echo "   NODE_OPTIONS = --max-old-space-size=512"
echo ""
echo "Please share the COMPLETE error message, not just the Node.js version line!"